/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUliRouteImport } from './routes/_app.uli'
import { Route as AppPortfolioRouteImport } from './routes/_app.portfolio'
import { Route as AppDemoRouteImport } from './routes/_app.demo'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCreditRouteImport } from './routes/_app.credit'
import { Route as AppAlertsRouteImport } from './routes/_app.alerts'
import { Route as AppMsmeIdRouteImport } from './routes/_app.msme.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUliRoute = AppUliRouteImport.update({
  id: '/uli',
  path: '/uli',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppDemoRoute = AppDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditRoute = AppCreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppMsmeIdRoute = AppMsmeIdRouteImport.update({
  id: '/msme/$id',
  path: '/msme/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/alerts': typeof AppAlertsRoute
  '/credit': typeof AppCreditRoute
  '/dashboard': typeof AppDashboardRoute
  '/demo': typeof AppDemoRoute
  '/portfolio': typeof AppPortfolioRoute
  '/uli': typeof AppUliRoute
  '/msme/$id': typeof AppMsmeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/alerts': typeof AppAlertsRoute
  '/credit': typeof AppCreditRoute
  '/dashboard': typeof AppDashboardRoute
  '/demo': typeof AppDemoRoute
  '/portfolio': typeof AppPortfolioRoute
  '/uli': typeof AppUliRoute
  '/msme/$id': typeof AppMsmeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/alerts': typeof AppAlertsRoute
  '/_app/credit': typeof AppCreditRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/demo': typeof AppDemoRoute
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/uli': typeof AppUliRoute
  '/_app/msme/$id': typeof AppMsmeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/alerts'
    | '/credit'
    | '/dashboard'
    | '/demo'
    | '/portfolio'
    | '/uli'
    | '/msme/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/alerts'
    | '/credit'
    | '/dashboard'
    | '/demo'
    | '/portfolio'
    | '/uli'
    | '/msme/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/alerts'
    | '/_app/credit'
    | '/_app/dashboard'
    | '/_app/demo'
    | '/_app/portfolio'
    | '/_app/uli'
    | '/_app/msme/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/uli': {
      id: '/_app/uli'
      path: '/uli'
      fullPath: '/uli'
      preLoaderRoute: typeof AppUliRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/demo': {
      id: '/_app/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof AppDemoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credit': {
      id: '/_app/credit'
      path: '/credit'
      fullPath: '/credit'
      preLoaderRoute: typeof AppCreditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts': {
      id: '/_app/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/msme/$id': {
      id: '/_app/msme/$id'
      path: '/msme/$id'
      fullPath: '/msme/$id'
      preLoaderRoute: typeof AppMsmeIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppCreditRoute: typeof AppCreditRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDemoRoute: typeof AppDemoRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppUliRoute: typeof AppUliRoute
  AppMsmeIdRoute: typeof AppMsmeIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppCreditRoute: AppCreditRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDemoRoute: AppDemoRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppUliRoute: AppUliRoute,
  AppMsmeIdRoute: AppMsmeIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
